version: "3"
services:
  fiap_database:
    container_name: fiap_database
    image: postgres
    environment:
      POSTGRES_DB: fiap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5440:5432"
